### ISSUE TITLE
Airgapped rmt deployment

### ISSUE THREAD

**Issue by ngetahun** [SUSE/helm-charts#11]
Enable air-gapped rmt deployment mode.  We need to change the following configurations to allow air-gapped deployments.
 
1. **SCC Credentials**: The necessity to add SCC credentials poses a challenge in an air-gapped environment. Currently, `rmt-cli sync` is run before server is started. The systemctl job `rmt-server-scc-sync.service` used to control background action.
 
2. **sync_systems Setting**: The `sync_systems` configuration is _hardcoded_ to true, preventing the use of RMT in offline mode as described in the documentation. We need to disable this during air-gap install mode.

**Comment by rafaprata** [comment]
@ngetahun I have a use-case that need to use this helm-chart on air-gapped environment. This PR is the same solution we used on our use-case.

**Comment by ngetahun** [comment]
closed by #12
